import type { Metadata } from "next";
import "./globals.css";
import Modal from "@/components/modal/Modal";
import { AppStoreProvider } from "@/store/AppStoreProvider";
import CustomToaster from "@/components/CustomToaster";
import { fontVariables } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppStoreProvider>
        <body className={`${fontVariables} antialiased overflow-x-clip`}>
          {children}
          <Modal />
          <CustomToaster />
        </body>
      </AppStoreProvider>
    </html>
  );
}
