import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Modal from "@/components/modal/Modal";
import { AppStoreProvider } from "@/store/AppStoreProvider";
import CustomToaster from "@/components/CustomToaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppStoreProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-clip`}>
          {children}
          <Modal />
          <CustomToaster />
        </body>
      </AppStoreProvider>
    </html>
  );
}
